### ISSUE TITLE
Workshop infrastructure

### ISSUE THREAD

**Issue by mblue9** [tidytranscriptomics-workshops/iscb2022_tidytranscriptomics#11]
Used same setup as for ISMB 2021, described [here](https://github.com/tidytranscriptomics-workshops/ismb2021_tidytranscriptomics/issues/1) 

Additional notes for this ISCB setup

_Packages_
```
packages="stemangiola/tidyseurat@v0.5.1 stemangiola/tidySingleCellExperiment@v1.3.2 tidytranscriptomics-workshops/iscb2022_tidytranscriptomics"

for i in $packages;
do
sudo R-install-package $i github;
done
```

Had error installing workshop package today
```
trying URL 'https://cran.ms.unimelb.edu.au/src/contrib/yaml_2.3.4.tar.gz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://cran.ms.unimelb.edu.au/src/contrib/yaml_2.3.4.tar.gz': HTTP status was '404 Not Found'
```
it wanted to install new yaml release which seems not available yet as only released today, worked around by uploading source & installing in R (`sudo R`):
`install.packages("yaml_2.3.4.tar.gz", repos = NULL, type="source")`

_Additional server_ 
As had already tested resources with one server (rstudio5) & 30 simulated users could just:
- deploy server (rstudio6) as per ISMB 2021
-  install packages as above
- `git clone https://github.com/tidytranscriptomics-workshops/iscb2022_tidytranscriptomics.git`
- `sudo cp -r iscb2022_tidytranscriptomics/ /etc/skel/`
-  upload workshop_setup folder containing scripts for creating user accounts
-  edit server number in workshop_setup/generate-accounts.sh
-  chmod +x workshop_setup/generate-accounts.sh
- `sudo workshop_setup/generate-accounts.sh > user-accounts.txt`

**Comment by stemangiola** [comment]
Uhh.. Is it not possible that the Unimelb mirror is out?

Do you want me to do anything?

**Comment by mblue9** [comment]
>Uhh.. Is it not possible that the Unimelb mirror is out?

Do you mean for that yaml error? No unimelb mirror is fine they just don't have the 2.3.4 version yet that the installation wanted, only 2.2.2. But I installed it from source and tested running in a couple of user accounts and all ran fine. So all good there.

>Do you want me to do anything?

Nope, just don't know why the pkgdown build step is hanging since last night so the actions/ website build isn't working. But not a big deal, we just may not have the slides (and DOI) in the website for the workshop but we have the link to the slides in the Google doc.

**Comment by mblue9** [comment]
Actually can you just doublecheck the updated code all runs ok for you on the server? Your login is in the spreadsheet, link is in the tutorial Google doc Batool sent us.

**Comment by stemangiola** [comment]
> Actually can you just doublecheck the updated code all runs ok for you on the server? Your login is in the spreadsheet, link is in the tutorial Google doc Batool sent us.

Sorry I know I'm the worst, could you paste here the spreadsheet link, I cannot find in the emails.

With the first login you gave me everything works btw.

**Comment by mblue9** [comment]
Have emailed you the spreadsheet 😃
