### ISSUE TITLE
seurat_modified[[]] causes website build to hang

### ISSUE THREAD

**Issue by mblue9** [tidytranscriptomics-workshops/iscb2022_tidytranscriptomics#12]
Just noting here that the failed actions since yesterday seem to have been caused by this line
`seurat_modified[[]]` 

For some reason the website build`pkgdown::build_site()` does not like that line and the actions here were running for >6hrs until cancelled by Github.

Have added `eval = FALSE` to that chunk for the moment.

Weird as don't know why that would cause that, just wondering if you do @stemangiola ?

**Comment by stemangiola** [comment]
Yes it's quite strange. We could open an issue in Seurat github repo. Or leave it for next workshop.

**Comment by mblue9** [comment]
I was going to open an issue in Seurat repo in case it needed fixing from Seurat end, as then it might be fixed by next workshop. But then thought maybe the issue was because that command outputs > 36k rows. 
It was! 
Viewing less rows works fine so I changed it to  `seurat_modified[[]] |> head()` ([here](https://github.com/tidytranscriptomics-workshops/iscb2022_tidytranscriptomics/commit/dd3fe7cf49321e7da629c1a41e4834555d5d8535))

**Comment by stemangiola** [comment]
You don't need me anymore ;)

Another good reason why to use tidyverse,  non of this xxx would happen

**Comment by mblue9** [comment]
> Another good reason why to use tidyverse,  non of this xxx would happen

Haha I was thinking the same
