### ISSUE TITLE
connection issues with ghcr.io

### ISSUE THREAD

**Issue by Emberwhirl** [tidytranscriptomics-workshops/iscb2022_tidytranscriptomics#13]
Hello. I am having issues with the connection to GitHub Packages Registry. Do you have any other options for downloading the docker image? Thank you so much.

**Comment by mblue9** [comment]
Glad you seem to have fixed it. If it happens again could you give us some details e.g. where you're connecting to ghcr.io from (AWS etc) to understand where/when this is an issue.
At the moment if the connection is not working then the other option would be to grab the [Dockerfile](https://github.com/tidytranscriptomics-workshops/iscb2022_tidytranscriptomics/blob/master/Dockerfile) and build the image yourself.

**Comment by Emberwhirl** [comment]
Thank you for the reply. And yes, I successfully built the image using the Dockerfile. Can't wait to give it a try.
